general.import = [ "tokyo-night.toml" ]

[terminal.shell]
args = ["-l"]
program = "/opt/homebrew/bin/fish"

[window]
blur = true
opacity = 0.8
padding.x = 14
padding.y = 14
decorations = "buttonless"

[font]
size = 12
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Italic" }

